BillRun_back/urls.py
from django.contrib import admin
from django.urls import path, include
from api.views import *
from django.conf.urls import url, static
from django.conf import settings
from rest_framework_jwt.views import obtain_jwt_token, verify_jwt_token, refresh_jwt_token
from .admin import admin_site

admin.autodiscover()

urlpatterns = [
    path('', main, name="main"),
    # path('admin/', admin.site.urls, name="admin"),
    path('admin/', admin_site.urls),
    path('api/', include('api.urls')),

    #jwt
    path('token/', obtain_jwt_token), #획득
    path('token/verify/', verify_jwt_token), #확인
    path('token/refresh/', refresh_jwt_token), #갱신

] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path, include
from rest_framework import urls
from rest_framework.routers import DefaultRouter
from .views import *
from django.conf.urls import url, static
from django.conf import settings

app_name='api'
router = DefaultRouter()
router.register('product', ProductViewSet, 'product')
router.register('lend', LendProductViewSet, 'lend')
router.register('rent', RentProductViewSet, 'rent')

urlpatterns = [
    ### Main
    path('', main, name="main"),
    path('main_user', main_user, name="main_user"),
    path('main_prodeal', main_prodeal, name="main_prodeal"),


    ### User
    path('user_list/', UserList.as_view(), name="user_list"),
    path('user_list/<int:user_id>', UserDetail.as_view(), name="user_detail"),


    ### Auth
    # 개발용 signin, signup
    path('signup/', UserCreate.as_view(), name="signup"),
    path('signin/', signin, name="signin"),
    # path('logout/', LogoutView.as_view(), name="logout"),

    # sms인증
    path('sms', SMSVerification.as_view(), name="sms"), #인증번호 전송
    path('sms_confirm', SMSConfirm.as_view(), name="sms_confirm"), #인증번호 확인

    # email인증
    path('email', EmailConfirm.as_view(), name="email"), #이메일 전송
    path('email/users/<str:uidb64>/<str:token>', activate), #유저 활성화
    path('user_active', activate_success, name="user_active"), #유저에게 활성화 완료 결과를 보여주는 페이지

    # Terms 약관동의
    path('terms/', TermsAgreement.as_view(), name="terms"),
    path('terms/<int:user_id>', UserTermsDetail.as_view(), name="terms_detail"), #유저의 약관동의 내역/일시 확인


    ### Product
    # 상품 등록
    path('product_post/', ProductPost.as_view(), name="product_post"),

    # 전체 상품 목록
    # path('product_list/', ProductList.as_view(), name="product_list"),
    # path('product_list/', product_list),
    path('product_list/', include(router.urls)),

    # 카테고리 별 상품 목록
    path('product/<str:ctgr>', ProductCategoryList.as_view(), name="product_ctgr"),

    # 물품 상세보기
    # path('product/<int:product_id>', ProductDetail.as_view(), name="product_detail"),
    # path('product/<int:product_id>', product_detail),

    # Lend 빌려드림
    # path('lend_product_list/', LendProductList.as_view(), name="lend_product_list"),
    # path('lend_product_list/<int:product_id>', ProductDetail.as_view(), name="lend_product_detail"), #물품 상세보기
    path('lend_product_list/user_id=<int:user_id>', UserLendProductList.as_view(), name="user_lend_product"), #특정 유저의 빌려드림 리스트
    
    # Rent 빌림
    # path('rent_product_list/', RentProductList.as_view(), name="rent_product_list"),
    # path('rent_product_list/<int:product_id>', ProductDetail.as_view(), name="rent_product_detail"), #물품 상세보기
    path('rent_product_list/user_id=<int:user_id>', UserRentProductList.as_view(), name="user_rent_product"), #특정 유저의 빌림 리스트

    # Like 좋아요 누르기 TODO 추가개발필요
    path('like/<int:product_id>', product_like_toggle, name="like_toggle"),


    ### Deal
    # 거래 진행
    path('deal_list/', DealList.as_view(), name="deal_list"),
    path('deal_list/<int:deal_id>', DealDetail.as_view(), name="deal_datail"),
    path('lend_deal_list/<int:user_id>', LendDealList.as_view(), name="lend_deal_list"),
    path('rent_deal_list/<int:user_id>', RentDealList.as_view(), name="rent_deal_list"),

    ### Review
    #물품리뷰 등록
    path('pro_review', ProductReviewPost.as_view(), name="pro_review"), 

    #특정 물품리뷰 상세보기
    path('review/pro_id=<int:product_id>', ProductReviewDetail.as_view(), name="pro_review_detail"), 

    #거래리뷰 등록(유저리뷰)
    path('deal_review', DealReviewPost.as_view(), name="deal_review"), 

    #특정 유저리뷰 상세보기
    path('review/user_id=<int:user_id>', UserReviewDetail.as_view(), name="user_review_detail"), 

    #특정 유저의 물품리뷰 상세보기
    path('prdt_review/user_id=<int:user_id>', UserProductReview.as_view(), name="user_prdt_review"),

    # Favorite 찜 목록
    path('favorite/', FavoriteList.as_view(), name="favorite_list"),
    path('favorite/<int:user_id>', FavoriteDetail.as_view(), name="favorite_detail"),

    # Notice 배너(공지사항, 이벤트)
    path('notice/', NoticeList.as_view(), name="notice"),
    path('notice/<int:notice_id>', NoticeDetail.as_view(), name="notice_detail"),

    # Chat
    path('chat/', chat_view, name="chat"), #채팅방 리스트
    path('chat/<int:chatroom_id>', ChatRoomDetail.as_view(), name="chatroom_detail"), #채팅방 상세보기
] 

api/views.py
# from django.core.checks import messages
from django.core.validators import validate_email
from django.db.models.query import Prefetch
# from django.http.response import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.utils.encoding import force_bytes, force_text
from rest_framework import viewsets
from rest_framework import permissions
from rest_framework.exceptions import ValidationError
from rest_framework.filters import SearchFilter
from rest_framework.viewsets import ModelViewSet
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status, generics
from .serializers import *
from .models import *
from django.core.mail import EmailMessage
# from django.contrib.sites.shortcuts import get_current_site #example.com
# from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.core.mail import EmailMessage
from .tokens import account_activation_token
from django.http import HttpResponse
from .auth_backend import PasswordlessAuthBackend
from cryptography.fernet import Fernet
# import bcrypt
import base64
# from .secret import ENCODE_KEY
from rest_framework.decorators import api_view, permission_classes
# from rest_framework_simplejwt.tokens import RefreshToken
from rest_framework.permissions import AllowAny
import json

##########################################################
# 빌림의 경우, Product의 user가 빌리미, Deal의 user가 드리미다    #
# 빌려드림의 경우, Product의 user가 드리미, Deal의 user가 빌리미다 #
##########################################################


# fernet = Fernet(ENCODE_KEY)

# # 핸드폰번호 암호화
# def encrypt_phone(phone):
#     phone_encrypted = fernet.encrypt(phone.encode())
#     # print(phone_encrypted)
#     # phone_encrypted = base64.b64encode(phone_encrypted)
#     # print(phone_encrypted)
#     # phone_encrypted = phone_encrypted.decode('ascii')

#     # print(phone_encrypted)

#     phone_encrypted = phone_encrypted.decode('utf8') #byte를 str로
#     # TypeError: token must be bytes
#     return phone_encrypted
#     # TypeError: Object of type bytes is not JSON serializable

# # 핸드폰번호 복호화
# def decrypt_phone(phone):
#     print(phone)
#     phone = phone.encode()
#     print(phone)
#     phone_decrypted = fernet.decrypt(phone)
#     print(phone_decrypted)
#     return phone_decrypted

# main page
def main(request):
    return render(request, 'api/main.html')

def main_user(request):
    return render(request, 'api/main_user.html')

def main_prodeal(request):
    return render(request, 'api/main_prodeal.html')

### Auth
# def	make_signature():
# 	timestamp = int(time.time() * 1000)
# 	timestamp = str(timestamp)

# 	access_key = ACCESS_KEY			# access key id (from portal or Sub Account)
# 	secret_key = SECRET_KEY				# secret key (from portal or Sub Account)
# 	secret_key = bytes(secret_key, 'UTF-8')

# 	method = "GET"
# 	uri = "/sms/v2/services/{SERVICE_ID}/messages"

# 	message = method + " " + uri + "\n" + timestamp + "\n" + access_key
# 	message = bytes(message, 'UTF-8')
# 	signingKey = base64.b64encode(hmac.new(secret_key, message, digestmod=hashlib.sha256).digest())
# 	return signingKey

@permission_classes([AllowAny])
class SMSVerification(APIView):
    def post(self, request):
        try:
            data = json.loads(request.body)
            phone = data['phone']
            # phone = encrypt_phone(data['phone'])
            AuthSms.objects.update_or_create(phone=phone)
            # AuthSms.objects.update_or_create(phone=data['phone'])
            return Response({'message': 'OK', 'status': Response.status_code})
        except KeyError:
            return Response({'message': 'Bad Request'}, status=status.HTTP_400_BAD_REQUEST)


@permission_classes([AllowAny])
class SMSConfirm(APIView):
    def post(self, request):
        try:
            data = json.loads(request.body)
            phone = data['phone']
            # phone = encrypt_phone(data['phone'])
            verification_number = data['auth_number']
            if verification_number == AuthSms.objects.get(phone=phone).auth_number:
                if not BillrunUser.objects.filter(phone=phone).exists(): # 해당핸드폰번호의 유저가 존재하지 않을 경우 유저 생성
                    return Response({'message': 'SUCCESS'}, status=200) # 번호인증 완료, 이메일인증 하면 됨
                else: # 해당 핸드폰번호의 유저가 존재할 경우 -> 로그인
                    ## Signin
                    # signin(request._request)
                    serializer = UserLoginSerializer(data=request.data)
                    user = BillrunUser.objects.get(phone=phone)
                    if not serializer.is_valid(raise_exception=True):
                        return Response({"message":"Request Body Error."}, status=status.HTTP_409_CONFLICT)
                    if serializer.validated_data['phone'] == "None":
                        return Response({"message": "fail"}, status=status.HTTP_200_OK)
                    response = {
                        'success': 'True',
                        'user': user.id,
                        'phone': user.phone,
                        'token': serializer.data['token']
                    }
                    return Response(response, status=status.HTTP_200_OK)
                # return Response({'message': 'REGISTERED_NUMBER'}, status=401)
            return Response({'message': '인증번호 오류'}, status=401) #인증번호 틀림
        except KeyError as e:
            return Response({'message': f'KEY_ERROR: {e}'}, status=400)
        except ValueError as e:
            return Response({'message': f'VALUE_ERROR: {e}'}, status=400)


## Terms 약관동의 
# class TermsList(APIView):
#     def get(self, request):
#         model = Terms.objects.all()
#         # serializer = UserSerializer(model, many=True)
#         serializer = TermsSerializer(model, context={'request': request}, many=True)
#         return Response(serializer.data)

@permission_classes([AllowAny])
class TermsAgreement(generics.CreateAPIView): #회원가입
    queryset = Terms.objects.all()
    serializer_class = TermsSerializer


class UserTermsDetail(APIView): 
    def get_user(self, user_id): #특정 유저 가져오기
        try:
            model = Terms.objects.get(user=user_id)
            model.save()
            return model
        except Terms.DoesNotExist:
            return

    def get(self, request, user_id):
        if not self.get_user(user_id):
            return Response(f'Terms with {user_id} is Not Found in database', status=status.HTTP_404_NOT_FOUND)
        serializer = TermsSerializer(self.get_user(user_id), context={'request': request})
        return Response(serializer.data)

    def put(self, request, user_id):
        if not self.get_user(user_id):
            return Response(f'Terms with {user_id} is Not Found in database', status=status.HTTP_404_NOT_FOUND)
        serializer = TermsSerializer(self.get_user(user_id), data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST) 


### Email 인증
def message(domain, uidb64, token):
    return f"아래 링크를 클릭하면 빌RUN 계정이 활성화됩니다. \n{domain}/users/{uidb64}/{token}\n\n감사합니다:) "

@permission_classes([AllowAny])
class EmailConfirm(APIView):
    def post(self, request):
        data = json.loads(request.body)
        try:
            validate_email(data['email'])
            if BillrunUser.objects.filter(email=data['email']).exists():
                return Response({"message":"EXISTS_EMAIL"}, status=400)
            phone = request.data['phone']
            community = request.data['community']
            email = request.data['email']
            user = BillrunUser.objects.create_user(
                phone=phone, 
                community = community,
                email = email,
                lat = 0,
                lng = 0
            )

            domain = request.build_absolute_uri()
            uidb64 = urlsafe_base64_encode(force_bytes(user.id))
            token = account_activation_token.make_token(user)
            message_data = message(domain, uidb64, token)

            title = '빌RUN 커뮤니티 인증 확인 이메일'
            email = EmailMessage(title, message_data, to=[email])
            email.send()
            return Response({
                'message': 'SUCCESS',
                'user': user.id
            }, status=200)
        
        except KeyError as e:
            return Response({'message': f'KEY_ERROR: {e}'}, status=400)
        except TypeError as e:
            return Response({'message': f'TYPE_ERROR: {e}'}, status=400)
        except ValidationError as e:
            return Response({'message': f'VALIDATION_ERROR: {e}'}, status=400)

# Email 인증 완료 -> 계정 활성화
def activate(request, uidb64, token):
    uid = force_text(urlsafe_base64_decode(uidb64))
    user = BillrunUser.objects.get(pk=uid)

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        user = PasswordlessAuthBackend.authenticate(phone=user.phone)
        try:
            payload = JWT_PAYLOAD_HANDLER(user)
            jwt_token = JWT_ENCODE_HANDLER(payload)
            update_last_login(None, user)
        except BillrunUser.DoesNotExist:
            raise serializers.ValidationError(
                'User with given phone number does not exists'
            )
        # auth.login(request, user)
        return redirect('api:user_active')
    else:
        return HttpResponse('비정상적인 접근입니다.')

def activate_success(request):
    return render(request, 'api/user_active.html')

#로그아웃
# class LogoutView(APIView):
#     permission_classes = (IsAuthenticated,)

#     def post(self, request):
#         try:
#             refresh_token = request.data["refresh_token"]
#             token = RefreshToken(refresh_token)
#             token.blacklist()

api/templates/api/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <!-- icon -->
    <link rel="shortcut icon" type="image⁄x-icon" href="https://cdn.shopify.com/s/files/1/1061/1924/products/Smiling_Devil_Emoji_large.png?v=1571606036">
    <title>BillRun</title>
  </head>
  <body>
    {% block content %}
    {% endblock %}
  </body>
</html>

api/templates/api/login.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/login.css" %}">
{{ form.media }}
{% endblock %}

{% block bodyclass %}{{ block.super }} login{% endblock %}

{% block usertools %}{% endblock %}

{% block nav-global %}{% endblock %}

{% block nav-sidebar %}{% endblock %}

{% block content_title %}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
{% if form.errors and not form.non_field_errors %}
<p class="errornote">
{% if form.errors.items|length == 1 %}{% translate "Please correct the error below." %}{% else %}{% translate "Please correct the errors below." %}{% endif %}
</p>
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="errornote">
    {{ error }}
</p>
{% endfor %}
{% endif %}

<div id="content-main">

{% if user.is_authenticated %}
<p class="errornote">
{% blocktranslate trimmed %}
    You are authenticated as {{ username }}, but are not authorized to
    access this page. Would you like to login to a different account?
{% endblocktranslate %}
</p>
{% endif %}

<form action="{{ app_path }}" method="post" id="login-form"> 
{% csrf_token %}
  <div class="form-row">
    {{ form.username.errors }}
    {{ form.username.label_tag }} {{ form.username }}
  </div>
  
  {% comment %} <input type="text" name="phone" class="form-control" /> {% endcomment %}

  {% comment %} <div class="form-row">
    {{ form.password.errors }}
    {{ form.password.label_tag }} {{ form.password }}
    <input type="hidden" name="next" value="{{ next }}">
  </div>

  {% url 'admin_password_reset' as password_reset_url %}
  {% if password_reset_url %}
  <div class="password-reset-link">
    <a href="{{ password_reset_url }}">{% translate 'Forgotten your password or username?' %}</a>
  </div>
  {% endif %} {% endcomment %}
  
  <div class="submit-row">
    <input type="submit" value="{% translate 'Log in' %}">
  </div> 
</form>

</div>
{% endblock %}

api/templates/api/main_user.html
{% extends 'api/base.html' %}
{% load static %}

{% block content %}
    <div class="container" style="margin-bottom:50px"> 
        <br>
        <h1 Align="center">😈 빌Run API 😈</h1>
        <br>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'api:main' %}">전체보기</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'api:main_user' %}"><b>회원</b></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'api:main_prodeal' %}">물품/거래</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/admin">Admin</a>
            </li>
        </ul>
        <div class="list-group">
        <div style="margin-top:10px; margin-bottom:20px">
            <h2>Auth</h2>
            <div class="row">
                <div class="col-sm-6">
                    <a href="{% url 'api:sms' %}" class="list-group-item list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">SMS 전송</h5>
                        </div>
                        <p class="mb-1">/api/sms</p>
                        <small>{"phone":"01012345678"} 입력 후 POST 방식으로 보내면 해당 번호로 인증 문자가 전송됩니다.</small>
                    </a>
                </div>
                <div class="col-sm-6">
                    <a href="{% url 'api:sms_confirm' %}" class="list-group-item list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">SMS 인증번호 확인</h5>
                        </div>
                        <p class="mb-1">/api/sms_confirm</p>
                        <small>{"phone":"01012345678", "auth_number":7695} 입력 후 인증번호가 맞고,<br>유저가 존재하지 않을 경우 -> 회원가입. 이메일 인증으로 이동해주세요<br>
                        유저가 존재할 경우 -> 로그인이 됩니다.</small>
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <a href="{% url 'api:email' %}" class="list-group-item list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">이메일 인증</h5>
                        </div>
                        <p class="mb-1">/api/email</p>
                        <small>phone, community, email 작성해서 POST 하면 회원이 생성됩니다.<br>이메일 인증까지 마치면 회원 활성화가 됩니다.</small>
                    </a>
                </div>
                <div class="col-sm-6">
                    <a href="{% url 'api:terms' %}" class="list-group-item list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">약관 동의</h5>
                        </div>
                        <p class="mb-1">/api/terms</p>
                        <small>유저의 약관동의 일자를 받습니다. 유저 생성과 동시에 데이터 저장하면 될 것 같습니다!<br>유저 id를 뒤에 붙이면 해당 유저의 동의 일시가 나옵니다.</small>
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <a href="{% url 'api:signup' %}" class="list-group-item list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">회원가입(개발용)</h5>
                        </div>
                        <p class="mb-1">/api/signup</p>
                        <small>폼에 맞게 입력하고 POST하면 회원가입이 됩니당. is_active 꼭 체크해주세요!</small>
                    </a>
                </div>
                <div class="col-sm-6">
                    <a href="{% url 'api:signin' %}" class="list-group-item list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">로그인(개발용)</h5>
                        </div>
                        <p class="mb-1">/api/signin</p>
                        <small>로그인 방법: {"phone":"01000000000"}</small>
                    </a>
                </div>
            </div>
            </div>
            <h2>User</h2>
            <div class="row">
                <div class="col-sm-6">
                    <a href="{% url 'api:user_list' %}" class="list-group-item list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">사용자 리스트</h5>
                        </div>
                        <p class="mb-1">/api/user_list</p>
                        <small>뒤에 User id 붙이면(/id) 해당 User의 정보가 나옵니다.</small>
                    </a>
                </div>
                <div class="col-sm-6">
                    <a href="{% url 'api:favorite_list' %}" class="list-group-item list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">사용자 좋아요 리스트</h5>
                        </div>
                        <p class="mb-1">/api/favorite/(int:user_id)</p>
                        <small>뒤에 User id 붙이면(/id) 해당 User의 좋아요 목록이 나옵니다.</small>
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <a href="{% url 'api:deal_review' %}" class="list-group-item list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">특정 유저에 대한 리뷰 작성 페이지</h5>
                        </div>
                        <p class="mb-1">/api/deal_review</p>
                        <small>실제로는 '거래'에 대한 리뷰입니다.<br>거래에 참여한 두 명의 유저만 작성할 수 있도록 추가개발할 예정입니다.</small>
                    </a>
                </div>
                <div class="col-sm-6">
                    <a href="{% url 'api:user_review_detail' user_id=1 %}" class="list-group-item list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">특정 유저에 대한 리뷰 리스트</h5>
                        </div>
                        <p class="mb-1">/api/review/user_id=(int:user_id)</p>
                        <small>예시로 user id=1인 '배가고프군그래' 값을 넣어두었습니다!</small>
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <a href="{% url 'api:user_lend_product' user_id=1 %}" class="list-group-item list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">특정 유저의 빌려드림 물품 리스트</h5>
                        </div>
                        <p class="mb-1">/api/lend_product_list/user_id=(int:user_id)</p>
                        <small>예시로 user id=1인 '배가고프군그래' 값을 넣어두었습니다!</small>
                    </a>
                </div>
                <div class="col-sm-6">
                    <a href="{% url 'api:user_rent_product' user_id=1 %}" class="list-group-item list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">특정 유저의 빌림 물품 리스트</h5>
                        </div>
                        <p class="mb-1">/api/lend_product_list/user_id=(int:user_id)</p>
                        <small>예시로 user id=1인 '배가고프군그래' 값을 넣어두었습니다!</small>
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <a href="{% url 'api:lend_deal_list' user_id=1 %}" class="list-group-item list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">특정 유저의 빌려드림 거래 리스트</h5>
                        </div>
                        <p class="mb-1">/api/lend_deal_list/(int:user_id)</p>
                        <small>예시로 user id=1인 '배가고프군그래' 값을 넣어두었습니다!</small>
                    </a>
                </div>
                <div class="col-sm-6">
                    <a href="{% url 'api:rent_deal_list' user_id=1 %}" class="list-group-item list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">특정 유저의 빌림 거래 리스트</h5>
                        </div>
                        <p class="mb-1">/api/rent_deal_list/(int:user_id)</p>
                        <small>예시로 user id=1인 '배가고프군그래' 값을 넣어두었습니다!</small>
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <a href="{% url 'api:user_prdt_review' user_id=30 %}" class="list-group-item list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">특정 유저에 대한 물품 리뷰 리스트</h5>
                        </div>
                        <p class="mb-1">/api/prdt_review/user_id=(int:user_id)</p>
                        <small>특정 유저의 id를 입력하면 해당 유저에 대한 물품 리뷰 리스트가 나옵니다. 예시 id값으로 30을 넣어두었습니다.</small>
                    </a>
                </div>
                <div class="col-sm-6">
                    <a href="{% url 'api:chat' %}" class="list-group-item list-group-item-action">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">채팅</h5>
                        </div>
                        <p class="mb-1">/api/chat</p>
                        <small>❗️Authorization 헤더 필요❗️<br>채팅 api입니다. 뒤에 숫자를 입력하면 해당 id의 채팅방을 볼 수 있습니다.</small>
                    </a>
                </div>
            </div>
        </div>
    </div>
    
{% endblock %}

api/templates/api/user_active.html
{% extends 'api/base.html' %}
{% load static %}

{% block content %}
<div class="container" style="text-Align:center; margin:50px">
    <h1>활성화 성공!<h1>
    <h3>앱에서 '인증 완료' 버튼을 눌러 가입을 완료해주세요 :)<h3>
</div>
{% endblock %}